### ISSUE TITLE
Error when building on Linux: qpa/qplatformnativeinterface.h: No such file or directory

### ISSUE THREAD

**Issue by mrplumber** [opentrack/opentrack#2113]
I've tried to build from most recent source. Got this error:

```
/opentrack/qxt-mini/qxtglobalshortcut_x11.cpp:40:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   40 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [qxt-mini/CMakeFiles/opentrack-qxt-mini.dir/build.make:127: qxt-mini/CMakeFiles/opentrack-qxt-mini.dir/qxtglobalshortcut_x11.cpp.o] Error 1
```

The file in question does actually exists on the system:

```
locate qplatformnativeinterface.h
/usr/include/qt6/QtGui/6.10.1/QtGui/qpa/qplatformnativeinterface.h
```

Cofigure command used:
`ONXXRuntime_ROOT=/home/user/build/onnxruntime-linux-x64-1.23.2/ cmake -B build -DCMAKE_INSTALL_PREFIX=$HOME/.local/ -DONNXRuntime_DIR=$HOME/build/onnxruntime-linux-x64-1.23.2/`

Might be related to #2112 

BTW, 3 days ago it compiled without errors.

**Comment by LaaZa** [comment]
Yes, this is the issue caused by #2112

**Comment by sthalik** [comment]
I can't reproduce it on Arch. Which distro are you having problems on? Anything specific about your configuration I need to replicate?

**Comment by mrplumber** [comment]
Also Arch, up to date, recently installed, quiet barebones. Followed opentrack Wiki instructions for building on Linux (whitch are outdated, needed to pull more build time dependencies, specifically _qt6-declarative_ package).

**Comment by mrplumber** [comment]
Also, I managed to successfully build it today, buy reverting change made with 226c182 commit, specifically to file `cmake/opentrack-qt.cmake`

Have no idea if this is the proper way though.

**Comment by mrplumber** [comment]
Latest code from Master branch builds without errors. Thank you.

**Comment by LevitatingBusinessMan** [comment]
this doesn't appear fixed for me on OpenSUSE Tumbleweed.

qt6 is at 6.10.1 for me

**Comment by sthalik** [comment]
@LevitatingBusinessMan what's the issue?

**Comment by LevitatingBusinessMan** [comment]
> [@LevitatingBusinessMan](https://github.com/LevitatingBusinessMan) what's the issue?

```
/home/rein/src/opentrack/qxt-mini/qxtglobalshortcut_x11.cpp:40:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   40 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [qxt-mini/CMakeFiles/opentrack-qxt-mini.dir/build.make:127: qxt-mini/CMakeFiles/opentrack-qxt-mini.dir/qxtglobalshortcut_x11.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3228: qxt-mini/CMakeFiles/opentrack-qxt-mini.dir/all] Error 2
```

**Comment by sthalik** [comment]
Have you installed `qt6-gui-private-devel`?

**Comment by LevitatingBusinessMan** [comment]
Ah, so that's what was missing! Thank you!

Maybe OpenSUSE build instructions would be helpful, they're slightly different from Fedora.

**Comment by jay-gates** [comment]
Work-around for Debian Trixie: install pkg qt6-base-private-dev
